package dev.johnoreilly.common.ui.global

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF4f0000)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFDADA)
internal val md_theme_light_onPrimaryContainer = Color(0xFF40000B)
internal val md_theme_light_secondary = Color(0xFF765657)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFFFDADA)
internal val md_theme_light_onSecondaryContainer = Color(0xFF2C1516)
internal val md_theme_light_tertiary = Color(0xFF755A2F)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFDDB0)
internal val md_theme_light_onTertiaryContainer = Color(0xFF281800)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFBFF)
internal val md_theme_light_onBackground = Color(0xFF201A1A)
internal val md_theme_light_surface = Color(0xFFFFFBFF)
internal val md_theme_light_onSurface = Color(0xFF201A1A)
internal val md_theme_light_surfaceVariant = Color(0xFFF4DDDD)
internal val md_theme_light_onSurfaceVariant = Color(0xFF524343)
internal val md_theme_light_outline = Color(0xFF857373)
internal val md_theme_light_inverseOnSurface = Color(0xFFFBEEED)
internal val md_theme_light_inverseSurface = Color(0xFF362F2F)
internal val md_theme_light_inversePrimary = Color(0xFFFFB3B4)
internal val md_theme_light_surfaceTint = Color(0xFF9F3E45)

internal val md_theme_dark_primary = Color(0xFFFFB3B4)
internal val md_theme_dark_onPrimary = Color(0xFF61101B)
internal val md_theme_dark_primaryContainer = Color(0xFF802730)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFFFDADA)
internal val md_theme_dark_secondary = Color(0xFFE6BDBD)
internal val md_theme_dark_onSecondary = Color(0xFF44292A)
internal val md_theme_dark_secondaryContainer = Color(0xFF5D3F40)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFFFDADA)
internal val md_theme_dark_tertiary = Color(0xFFE6C18D)
internal val md_theme_dark_onTertiary = Color(0xFF422C05)
internal val md_theme_dark_tertiaryContainer = Color(0xFF5B421A)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB0)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF201A1A)
internal val md_theme_dark_onBackground = Color(0xFFECE0DF)
internal val md_theme_dark_surface = Color(0xFF201A1A)
internal val md_theme_dark_onSurface = Color(0xFFECE0DF)
internal val md_theme_dark_surfaceVariant = Color(0xFF524343)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C1)
internal val md_theme_dark_outline = Color(0xFF9F8C8C)
internal val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
internal val md_theme_dark_inverseSurface = Color(0xFFECE0DF)
internal val md_theme_dark_inversePrimary = Color(0xFF9F3E45)
internal val md_theme_dark_surfaceTint = Color(0xFFFFB3B4)

internal val maroon200 = Color(0xFFb73d2a)
internal val lowfidelitygray = Color(0xFFEBEBEB)
