name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Run Detekt
      run: ./gradlew detektDebugAndroid
    - name: Upload Detekt SARIF Report
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: common/build/reports/detekt/detektDebugAndroid.sarif
    - name: Build android app
      run: ./gradlew assembleDebug
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Build iOS shared code
      run: ./gradlew :common:compileKotlinIosSimulatorArm64

